### ISSUE TITLE
GET ALL Simulation Campaigns doesn't support `within_brain_region_brain_region_id` yet it is exposed

### ISSUE THREAD

**Issue by WonderPG** [openbraininstitute/entitycore#487]
## Environment
staging

## Description
Trying to query the `GET ALL Simulation Campaigns` endpoint with the following body:
```
{
  "page": 1,
  "page_size": 10,
  "within_brain_region_brain_region_id": "5fac971a-8018-4844-933f-3b0a22f7d343"
}
```
raises the following error
```
File \"/code/app/filters/brain_region.py\", line 89, in filter_by_hierarchy_and_region\n    query = query.join(brain_region_query, model.brain_region_id == brain_region_query.c.id)\n                                           ^^^^^^^^^^^^^^^^^^^^^\nAttributeError: type object 'SimulationCampaign' has no attribute 'brain_region_id'\n"
```

It seems like simulation campaigns are not made to be filter by brain region since they are not scientific artifacts. However, I would argue that it could be an interesting feature (e.g. from the chat "Show me my simulation campaigns from the Cortical Plate").

## Expected behavior
The request goes through

**Comment by mgeplf** [comment]
> endpoint with the following body:

What do you mean `body` in this case?

Could you please include the full query?

When I do:
```
https://staging.openbraininstitute.org/api/entitycore/simulation-campaign?within_brain_region_brain_region_id=5fac971a-8018-4844-933f-3b0a22f7d343 
```
I seem to get a response.

**Comment by WonderPG** [comment]
Sorry body was the wrong word, I meant query parameters

**Comment by mgeplf** [comment]
This has been deployed in staging, so the endpoints that don't take `within_brain_region_brain_region_id` no longer advertise that they do - sorry about that.

If the ability to filter by `within_brain_regions`, I think we'll have to make a new ticket and prioritize that work separately.
